[package]
name = "sumeitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
text_io = "0.1.10"
crossterm = "0.23.2"
chrono = "0.4.19"
home = "0.5.3"
